src/Entity/Fournisseur.php
<?php

namespace App\Entity;

use App\Repository\FournisseurRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FournisseurRepository::class)]
class Fournisseur extends Personne
{
  

    #[ORM\Column(nullable: true)]
    private ?int $fournisseur_fournisseur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $produits_fourn = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFournisseurNFournisseur(): ?int
    {
        return $this->fournisseurN_fournisseur;
    }

    public function setFournisseurNFournisseur(?int $fournisseurN_fournisseur): static
    {
        $this->fournisseurN_fournisseur = $fournisseurN_fournisseur;

        return $this;
    }

    public function getProduitsFourn(): ?string
    {
        return $this->produits_fourn;
    }

    public function setProduitsFourn(?string $produits_fourn): static
    {
        $this->produits_fourn = $produits_fourn;

        return $this;
    }

    #[ORM\OneToMany(targetEntity: Produit::class, mappedBy: 'fournisseur')]
    private Collection $produitsFournis;

    public function __construct() {
        $this->produitsFournis = new ArrayCollection();
    }
}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use App\Entity\Fournisseur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('fournisseurN_fournisseur')
            ->add('produits_fourn')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fournisseur::class,
        ]);
    }
}

src/Controller/FournisseurController.php
<?php

namespace App\Controller;

use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Repository\FournisseurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fournisseur')]
class FournisseurController extends AbstractController
{
    #[Route('/', name: 'app_fournisseur_index', methods: ['GET'])]
    public function index(FournisseurRepository $fournisseurRepository): Response
    {
        return $this->render('fournisseur/index.html.twig', [
            'fournisseurs' => $fournisseurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fournisseur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $fournisseur = new Fournisseur();
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($fournisseur);
            $entityManager->flush();

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('fournisseur/new.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_show', methods: ['GET'])]
    public function show(Fournisseur $fournisseur): Response
    {
        return $this->render('fournisseur/show.html.twig', [
            'fournisseur' => $fournisseur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fournisseur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fournisseur $fournisseur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('fournisseur/edit.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_delete', methods: ['POST'])]
    public function delete(Request $request, Fournisseur $fournisseur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fournisseur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($fournisseur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/fournisseur/_delete_form.html.twig
<form method="post" action="{{ path('app_fournisseur_delete', {'id': fournisseur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fournisseur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fournisseur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fournisseur/edit.html.twig
<!DOCTYPE html>

<title>Edit Fournisseur</title>

{% block body %}
    <h1>Edit Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}

templates/fournisseur/index.html.twig
<!DOCTYPE html>

<title>Fournisseur index</title>

{% block body %}
    <h1>Fournisseur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Telephone</th>
                <th>FournisseurN_fournisseur</th>
                <th>Produits_fourn</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fournisseur in fournisseurs %}
            <tr>
                <td>{{ fournisseur.id }}</td>
                <td>{{ fournisseur.nom }}</td>
                <td>{{ fournisseur.prenom }}</td>
                <td>{{ fournisseur.telephone }}</td>
                <td>{{ fournisseur.fournisseurNFournisseur }}</td>
                <td>{{ fournisseur.produitsFourn }}</td>
                <td>
                    <a href="{{ path('app_fournisseur_show', {'id': fournisseur.id}) }}">show</a>
                    <a href="{{ path('app_fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fournisseur_new') }}">Create new</a>
{% endblock %}

templates/fournisseur/new.html.twig
<!DOCTYPE html>

<title>New Fournisseur</title>

{% block body %}
    <h1>Create new Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig') }}

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>
{% endblock %}

templates/fournisseur/show.html.twig
<!DOCTYPE html>

<title>Fournisseur</title>

{% block body %}
    <h1>Fournisseur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fournisseur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ fournisseur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ fournisseur.prenom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ fournisseur.telephone }}</td>
            </tr>
            <tr>
                <th>FournisseurN_fournisseur</th>
                <td>{{ fournisseur.fournisseurNFournisseur }}</td>
            </tr>
            <tr>
                <th>Produits_fourn</th>
                <td>{{ fournisseur.produitsFourn }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>

    <a href="{{ path('app_fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}