src/Entity/Achat.php
<?php

namespace App\Entity;

use App\Repository\AchatRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AchatRepository::class)]
class Achat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $N_achat = null;

    #[ORM\Column(length: 255)]
    private ?string $produit_achteté = null;

  

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_dachat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNAchat(): ?int
    {
        return $this->N_achat;
    }

    public function setNAchat(int $N_achat): static
    {
        $this->N_achat = $N_achat;

        return $this;
    }

    public function getProduitAchteté(): ?string
    {
        return $this->produit_achteté;
    }

    public function setProduitAchteté(string $produit_achteté): static
    {
        $this->produit_achteté = $produit_achteté;

        return $this;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getDateDachat(): ?\DateTimeInterface
    {
        return $this->date_dachat;
    }

    public function setDateDachat(\DateTimeInterface $date_dachat): static
    {
        $this->date_dachat = $date_dachat;

        return $this;
    }
    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'achats')]
    #[ORM\JoinColumn(name: 'client_id', referencedColumnName: 'id')]
    private ?Client $client;


    private $pricingStrategy;

    public function __construct(PricingStrategy $strategy) {
        $this->pricingStrategy = $strategy;
    }

    public function finalizePurchase($amount) {
        return $this->pricingStrategy->calculatePrice($amount);
    }
}

src/Form/AchatType.php
<?php

namespace App\Form;

use App\Entity\Achat;
use App\Entity\Client;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AchatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('N_achat')
            ->add('produit_achteté')
            ->add('date_dachat')
            ->add('client', EntityType::class, [
                'class' => Client::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Achat::class,
        ]);
    }
}

src/Controller/AchatController.php
<?php

namespace App\Controller;

use App\Entity\Achat;
use App\Form\AchatType;
use App\Repository\AchatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/achat')]
class AchatController extends AbstractController
{
    #[Route('/', name: 'app_achat_index', methods: ['GET'])]
    public function index(AchatRepository $achatRepository): Response
    {
        return $this->render('achat/index.html.twig', [
            'achats' => $achatRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_achat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $achat = new Achat();
        $form = $this->createForm(AchatType::class, $achat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($achat);
            $entityManager->flush();

            return $this->redirectToRoute('app_achat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('achat/new.html.twig', [
            'achat' => $achat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_achat_show', methods: ['GET'])]
    public function show(Achat $achat): Response
    {
        return $this->render('achat/show.html.twig', [
            'achat' => $achat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_achat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Achat $achat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AchatType::class, $achat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_achat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('achat/edit.html.twig', [
            'achat' => $achat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_achat_delete', methods: ['POST'])]
    public function delete(Request $request, Achat $achat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$achat->getId(), $request->request->get('_token'))) {
            $entityManager->remove($achat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_achat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/achat/_delete_form.html.twig
<form method="post" action="{{ path('app_achat_delete', {'id': achat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ achat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/achat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/achat/edit.html.twig
<!DOCTYPE html>

<title>Edit Achat</title>

{% block body %}
    <h1>Edit Achat</h1>

    {{ include('achat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_achat_index') }}">back to list</a>

    {{ include('achat/_delete_form.html.twig') }}
{% endblock %}

templates/achat/index.html.twig
<!DOCTYPE html>

<title>Achat index</title>

{% block body %}
    <h1>Achat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>N_achat</th>
                <th>Produit_achteté</th>
                <th>Date_dachat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for achat in achats %}
            <tr>
                <td>{{ achat.id }}</td>
                <td>{{ achat.NAchat }}</td>
                <td>{{ achat.produitAchteté }}</td>
                <td>{{ achat.dateDachat ? achat.dateDachat|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_achat_show', {'id': achat.id}) }}">show</a>
                    <a href="{{ path('app_achat_edit', {'id': achat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_achat_new') }}">Create new</a>
{% endblock %}

templates/achat/new.html.twig
<!DOCTYPE html>

<title>New Achat</title>

{% block body %}
    <h1>Create new Achat</h1>

    {{ include('achat/_form.html.twig') }}

    <a href="{{ path('app_achat_index') }}">back to list</a>
{% endblock %}

templates/achat/show.html.twig
<!DOCTYPE html>

<title>Achat</title>

{% block body %}
    <h1>Achat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ achat.id }}</td>
            </tr>
            <tr>
                <th>N_achat</th>
                <td>{{ achat.NAchat }}</td>
            </tr>
            <tr>
                <th>Produit_achteté</th>
                <td>{{ achat.produitAchteté }}</td>
            </tr>
            <tr>
                <th>Date_dachat</th>
                <td>{{ achat.dateDachat ? achat.dateDachat|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_achat_index') }}">back to list</a>

    <a href="{{ path('app_achat_edit', {'id': achat.id}) }}">edit</a>

    {{ include('achat/_delete_form.html.twig') }}
{% endblock %}